In [5]:
import pandas as pd
import numpy as np

In [6]:
df=pd.read_csv("../data/Reviews.csv")
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [3]:
df.shape

(568454, 10)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568454 non-null  int64
 1   ProductId               568454 non-null  object
 2   UserId                  568454 non-null  object
 3   ProfileName             568428 non-null  object
 4   HelpfulnessNumerator    568454 non-null  int64
 5   HelpfulnessDenominator  568454 non-null  int64
 6   Score                   568454 non-null  int64
 7   Time                    568454 non-null  int64
 8   Summary                 568427 non-null  object
 9   Text                    568454 non-null  object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB

In [5]:
df=df[["Score","Text"]]
df.head()

   Score                                               Text
0      5  I have bought several of the Vitality canned d...
1      1  Product arrived labeled as Jumbo Salted Peanut...
2      4  This is a confection that has been around a fe...
3      2  If you are looking for the secret ingredient i...
4      5  Great taffy at a great price.  There was a wid...

In [7]:
def map_sentiment(Score):
    if Score <=2:
        return "Negative"
    elif Score ==3:
        return "Neutral"
    else:
        return "Positive"
df["sentiment"]=df["Score"].apply(map_sentiment)

In [7]:
df.head()

   Score                                               Text sentiment
0      5  I have bought several of the Vitality canned d...  Positive
1      1  Product arrived labeled as Jumbo Salted Peanut...  Negative
2      4  This is a confection that has been around a fe...  Positive
3      2  If you are looking for the secret ingredient i...  Negative
4      5  Great taffy at a great price.  There was a wid...  Positive

In [8]:
df["Text"].iloc[6]

"This saltwater taffy had great flavors and was very soft and chewy.  Each candy was individually wrapped well.  None of the candies were stuck together, which did happen in the expensive version, Fralinger's.  Would highly recommend this candy!  I served it at a beach-themed party and everyone loved it!"

In [9]:
df["review_length"]=df["Text"].apply(len)
df["review_length"].describe()

count    568454.000000
mean        436.222083
std         445.339741
min          12.000000
25%         179.000000
50%         302.000000
75%         527.000000
max       21409.000000
Name: review_length, dtype: float64

In [8]:
df["sentiment"].value_counts(normalize=True)

sentiment
Positive    0.780674
Negative    0.144316
Neutral     0.075010
Name: proportion, dtype: float64

In [9]:
import re

def clean(text):
    text=text.lower()

    text=re.sub(r"<.*?>","",text)

    text= re.sub(r"http\S+|www\S+", "", text)

    text = re.sub(r"[^a-z\s]", "", text)

    text = re.sub(r"\s+", " ", text).strip()
    
    return text

In [10]:
df["clean_review"]=df["Text"].apply(clean)
df[["Text","clean_review"]].tail()

,Text,clean_review
568449,Great for sesame chicken..this is a good if no...,great for sesame chickenthis is a good if not ...
568450,I'm disappointed with the flavor. The chocolat...,im disappointed with the flavor the chocolate ...
568451,"These stars are small, so you can give 10-15 o...",these stars are small so you can give of those...
568452,These are the BEST treats for training and rew...,these are the best treats for training and rew...
568453,"I am very satisfied ,product is as advertised,...",i am very satisfied product is as advertised i...

In [11]:
import nltk
nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ojas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Ojas\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [12]:
from nltk.corpus import stopwords
stop_words= set(stopwords.words("english"))

def tok_and_remove_stopwords(text):
    tokens=text.split()
    tokens= [word for word in tokens if word not in stop_words]
    return tokens

In [13]:
df["tokens"]=df["clean_review"].apply(tok_and_remove_stopwords)

In [15]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text,sentiment,clean_review,tokens
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...,Positive,i have bought several of the vitality canned d...,"[bought, several, vitality, canned, dog, food,..."
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...,Negative,product arrived labeled as jumbo salted peanut...,"[product, arrived, labeled, jumbo, salted, pea..."
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...,Positive,this is a confection that has been around a fe...,"[confection, around, centuries, light, pillowy..."
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...,Negative,if you are looking for the secret ingredient i...,"[looking, secret, ingredient, robitussin, beli..."
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...,Positive,great taffy at a great price there was a wide ...,"[great, taffy, great, price, wide, assortment,..."

In [16]:
from nltk.stem import  WordNetLemmatizer

lemmatizer= WordNetLemmatizer()

def lemm_tokens(tokens):
    return[lemmatizer.lemmatize(token) for token in tokens]

In [17]:
df["lemmatized_tokens"]=df["tokens"].apply(lemm_tokens)

In [18]:
df[["tokens","lemmatized_tokens"]].tail()

,tokens,lemmatized_tokens
568449,"[great, sesame, chickenthis, good, better, res...","[great, sesame, chickenthis, good, better, res..."
568450,"[im, disappointed, flavor, chocolate, notes, e...","[im, disappointed, flavor, chocolate, note, es..."
568451,"[stars, small, give, one, training, session, t...","[star, small, give, one, training, session, tr..."
568452,"[best, treats, training, rewarding, dog, good,...","[best, treat, training, rewarding, dog, good, ..."
568453,"[satisfied, product, advertised, use, cereal, ...","[satisfied, product, advertised, use, cereal, ..."

In [19]:
df["proccessed_text"]=df["lemmatized_tokens"].apply(lambda x:" " .join(x) )
df[["proccessed_text","Text"]].head()

,proccessed_text,Text
0,bought several vitality canned dog food produc...,I have bought several of the Vitality canned d...
1,product arrived labeled jumbo salted peanutsth...,Product arrived labeled as Jumbo Salted Peanut...
2,confection around century light pillowy citrus...,This is a confection that has been around a fe...
3,looking secret ingredient robitussin believe f...,If you are looking for the secret ingredient i...
4,great taffy great price wide assortment yummy ...,Great taffy at a great price. There was a wid...

In [21]:
from sklearn.model_selection import train_test_split

x=df["proccessed_text"]
y=df["sentiment"]

X_train,X_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.25,
    stratify=y,
    random_state=42
)

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf= TfidfVectorizer(
    max_features=20000,
    ngram_range=(1,2),
    min_df=5,
    max_df=0.9,              
    sublinear_tf=True 
)
X_train_Tfid=tfidf.fit_transform(X_train)
X_test_Tfid=tfidf.transform(X_test)

In [23]:
type(sklearn.feature_extraction.text)

NameError: name 'sklearn' is not defined

In [33]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression(
    max_iter=100,
    class_weight ="balanced"
)
log.fit(X_train_Tfid,y_train)

c:\Users\Ojas\Desktop\customer-review-intelligence\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced')

In [25]:
from sklearn.metrics import confusion_matrix, classification_report

y_pred= log.predict(X_test_Tfid)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[15861  3514  1134]
 [ 1982  7232  1446]
 [ 5567 12592 92786]]
              precision    recall  f1-score   support

    Negative       0.68      0.77      0.72     20509
     Neutral       0.31      0.68      0.43     10660
    Positive       0.97      0.84      0.90    110945

    accuracy                           0.82    142114
   macro avg       0.65      0.76      0.68    142114
weighted avg       0.88      0.82      0.84    142114

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
Cvect= CountVectorizer(
    max_features=20000,
    ngram_range=(1,2),
    min_df=5
)
X_train_Count=Cvect.fit_transform(X_train)
X_test_Count=Cvect.fit_transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(
    max_iter=100,
    class_weight="balanced"
    

)
model.fit(X_train_Count,y_train)

c:\Users\Ojas\Desktop\customer-review-intelligence\venv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced')

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
y_pred_count=model.predict(X_test_Count)
print(confusion_matrix(y_test,y_pred_count),classification_report(y_test,y_pred_count))

[[ 4718  2991 12800]
 [ 2425  1666  6569]
 [22583 19148 69214]]               precision    recall  f1-score   support

    Negative       0.16      0.23      0.19     20509
     Neutral       0.07      0.16      0.10     10660
    Positive       0.78      0.62      0.69    110945

    accuracy                           0.53    142114
   macro avg       0.34      0.34      0.33    142114
weighted avg       0.64      0.53      0.58    142114

In [ ]:
from sklearn.svm import LinearSVC
svm_model=LinearSVC(
    class_weight="balanced"
)
svm_model.fit(X_train_Tfid,y_train)

LinearSVC(class_weight='balanced')

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
y_pred_svm=svm_model.predict(X_test_Tfid)
print(classification_report(y_test,y_pred_svm))

print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

    Negative       0.16      0.13      0.14     20509
     Neutral       0.07      0.06      0.07     10660
    Positive       0.78      0.82      0.80    110945

    accuracy                           0.67    142114
   macro avg       0.34      0.34      0.34    142114
weighted avg       0.64      0.67      0.65    142114

              precision    recall  f1-score   support

    Negative       0.16      0.13      0.14     20509
     Neutral       0.07      0.06      0.07     10660
    Positive       0.78      0.82      0.80    110945

    accuracy                           0.67    142114
   macro avg       0.34      0.34      0.34    142114
weighted avg       0.64      0.67      0.65    142114

In [34]:
from sklearn.svm import LinearSVC

final_svm = LinearSVC(
    class_weight="balanced",
    random_state=42
)
final_svm.fit(X_train_Tfid,y_train)

LinearSVC(class_weight='balanced', random_state=42)

In [27]:
from sklearn.metrics import confusion_matrix, classification_report
y_pred_final=final_svm.predict(X_test_Tfid)
print (confusion_matrix(y_test,y_pred_final))
print (classification_report(y_test,y_pred_final))

[[ 16049   2181   2279]
 [  2203   5645   2812]
 [  3655   4857 102433]]
              precision    recall  f1-score   support

    Negative       0.73      0.78      0.76     20509
     Neutral       0.45      0.53      0.48     10660
    Positive       0.95      0.92      0.94    110945

    accuracy                           0.87    142114
   macro avg       0.71      0.75      0.73    142114
weighted avg       0.88      0.87      0.88    142114

In [35]:
import joblib
import os
os.makedirs("../models",exist_ok=True)

joblib.dump(tfidf,"../models/tfidf_vectorizer.pkl")
joblib.dump(final_svm,"../models/sentiment_svm_model.pkl")

['../models/sentiment_svm_model.pkl']

In [29]:
import os
os.makedirs("../src",exist_ok=True)

In [30]:
import sys
sys.path.append("../src")

from preprocessing import clean_text

sample = df["Text"].iloc[0]
print(sample)
print(clean_text(sample))

I have bought several of the Vitality canned dog food products and have found them all to be of good quality. The product looks more like a stew than a processed meat and it smells better. My Labrador is finicky and she appreciates this product better than  most.
bought several vitality canned dog food product found good quality product look like stew processed meat smell better labrador finicky appreciates product better